### ISSUE TITLE
Not quite compatible with UPBox

### ISSUE THREAD

**Issue by adrianbear** [MaikStohn/UP3D#13]
I have conducted some system testing against the UPBox! (Rom V6.110 and Firmware V3.38)
The transcoder transcodes gcode to up code (.umc) with no problem.
The uploader uploads the .umc file, no problems apparent.
The UPBox! starts processing and regardless of current position moves the print head forward (towards the door in the Y axis) until it grinds (at which point I turn the printer off).

I started by testing with an UP Bunny sliced from Simplify3d
I then stripped the gcode down to just the first command (G90), same result.
I then stripped the input.gcode file to no commands (i.e. an empty file), same result.

I was able to use the "alternate UP software" control panel (in ModelWizard) to move the print head and bed, but I also got the message "Unsupported printer" when I tried to print from it.
My conclusion is the transcoding of gcode to UPCommands should be fine, but the .umc file header needs to be coded to specifically suit the UP printer model or something like that.

I saw you have added a new tool "upinfo.exe". I have executed it and output the results to a text file that I have attached to this issue.

I hope this helps?
If there is more information that you need or testing, please let me know.

Thanks
Adrian
[upinfoOutput.txt](https://github.com/MaikStohn/UP3D/files/218899/upinfoOutput.txt)

**Comment by MaikStohn** [comment]
Thanks for your info.

We already have another issue dealing with differences between UP-Mini and other UP printers:

-->  issue #11
