### ISSUE TITLE
Version 0.4.0 appears to be broken

### ISSUE THREAD

**Issue by adrianbear** [MaikStohn/UP3D#16]
Hi Maik,
It appears the "UP3DTOOLS_WIN_20160426_v0.4.0" transcoder is broken. It just hangs. Previous version still runs though so its not something local.
![v040hangs](https://cloud.githubusercontent.com/assets/6194143/14884170/22f25b68-0d82-11e6-8a32-76030829d63c.png)
Adrian

**Comment by MaikStohn** [comment]
Hi,

Sorry for this. I just learned that Windows has bug with the standard file io functions... never thought of that. I added a workaround and a new release (0.4.1), available in a few minutes.

Maik
