### ISSUE TITLE
update ipk of upwifi

### ISSUE THREAD

**Issue by DiegoGiovany** [MaikStohn/UP3D#19]
Hi, I have problems cross-compiling the up3dwifisrv with osx,  can you update the ipk?  my printer works, but, shows as "TEST2" name and aways give a connection error at first....

Thanks

**Comment by MaikStohn** [comment]
For compiling OpenWRT things I strongly recommend to setup a Linux (I use ubuntu or debian) in a virtual machine. VirtualBox is free and handles the job good.

I will update the IPK after I finished some more work on the WiFi part, maybe somewhen next week.

Maik

**Comment by MaikStohn** [comment]
I updated the IPK file.
