### ISSUE TITLE
Question / Issue : convg does not produce sensible gcode in preview

### ISSUE THREAD

**Issue by adrianbear** [MaikStohn/UP3D#25]
Hi,
I've just compiled up the convg tool and run it over the MemDump.dat file from FixUp3d.
The MemDump.dat was generated from a simple 10x20 cylinder print.
I then previewed the resulting gcode in Simplify3d. The preview shows the print head going all over the place.
![image](https://cloud.githubusercontent.com/assets/6194143/15090423/aadc0a8e-1466-11e6-9314-da9c4c162236.png)

I also ran the convg tool over the upcode generated file from up3dtranscode. Ie from gcode to upcode and back to gcode again.
The preview is even worse again.
Below is a preview of the source gcode
![image](https://cloud.githubusercontent.com/assets/6194143/15090445/1c0826c0-1467-11e6-9a3b-2e86381bc853.png)

After transcoding and then converting back to gcode again it looks like this
![image](https://cloud.githubusercontent.com/assets/6194143/15090452/4e4b702e-1467-11e6-9d04-be4b9c4b8ea4.png)

I understand that the transcoder "mostly" works, so why can't we convert back and forth and get the same results?

Thanks
Adrian

**Comment by MaikStohn** [comment]
Hi,

convg is a small test tool. It has hard coded the steps/mm for UP-Mini (854.0).

When you use it with other machine codes (e.g. UP-Box) you must change the steps/mm.

E.g. for UP-Box change:
```
#define STEPS_X (854.0)
#define STEPS_Y (854.0)
#define STEPS_E (854.0)
```
to
```
#define STEPS_X (644.0)
#define STEPS_Y (644.0)
#define STEPS_E (854.0)
```
STEPS E is same for both types.


Then output will be correct for your machine program.

Maik

**Comment by adrianbear** [comment]
Hi Maik,

Right you are :) All good now I've adjusted the X Y step constants in the programs.

Thanks
Adrian
