### ISSUE TITLE
Question / Issue: convg tool travel moves

### ISSUE THREAD

**Issue by adrianbear** [MaikStohn/UP3D#27]
Hi,
It appears the convg tool does not differentiate between print and travel moves.
I have converted a gcode file from Simplify3d to upcode and then back to gcode and the Simplify3d previewer shows the travel only lines in with the normal print lines (i.e. even when I uncheck the "Travel moves" check box). It does not do this on the original gcode file though.

![image](https://cloud.githubusercontent.com/assets/6194143/15101580/3781eaa4-15d3-11e6-8112-77be68f056fa.png)

I am hoping this is an insignificant bug in the convg tool and not a bug in the transcoder?

Thanks
Adrian

**Comment by MaikStohn** [comment]
Hi,

It's not convg,it is your viewer (Simplify3D) which does not differentiate between them. 
In their own gcode to put a lot of comments to distinguish between features types and move types.

If you use RepetierHost for viewing the G-Code it will differentiate correctly between them.

Maik
