### ISSUE TITLE
Layer Positioning Issue

### ISSUE THREAD

**Issue by adrianbear** [MaikStohn/UP3D#28]
Hi @MaikStohn, @kscheff,
Testing version "UP3DTOOLS_WIN_20160508_v0.6.2" with my UPBox, there is an issue with the layer positioning.
The error can be seen both in a real print and when converting back to gcode.
This is the original preview
![image](https://cloud.githubusercontent.com/assets/6194143/15146606/97936020-16fb-11e6-865d-3a5c24816257.png)

After converting to up code and then back to gcode, the preview looks like this
![image](https://cloud.githubusercontent.com/assets/6194143/15146660/d0001e26-16fb-11e6-8e8c-528a4f399aa1.png)

I considered this may just be an issue with the preview only from converting back and forth so I printed it anyway, but the real print has the layers off too.
![wp_20160510_005](https://cloud.githubusercontent.com/assets/6194143/15146882/c8c8b158-16fc-11e6-9d40-65fa7a1ce5ff.jpg)
![wp_20160510_004](https://cloud.githubusercontent.com/assets/6194143/15146895/d3ff0b76-16fc-11e6-906f-40e5aca25caa.jpg)

Adrian

The files might help :), I couldn't zip everything so I excluded the upcode and the converted back to gcode files (as I figured you could reproduce them with your tools anyway)
[LayerPositioningIssue.zip](https://github.com/MaikStohn/UP3D/files/257222/LayerPositioningIssue.zip)

**Comment by MaikStohn** [comment]
Thanks for the files.

Will have a look at them. The problem seems to be very very small segments (time wise), This only seems to happen when your speed is very slow.

**Comment by adrianbear** [comment]
The print shown here was done at 3600 mm/min which is only a bit slower then the UPBox turbo speed  on a 0.4 mm layer height (5020 mm/min).
I also originally tried the print at 4800 mm/min but got the same result.

**Comment by MaikStohn** [comment]
I will have a look as soon as I find some time for it.

**Comment by MaikStohn** [comment]
Hi,

this was a tricky one. Actually everything was working perfect except a small thing. The absolute Z-move for layer change was not synchronized with the normal movement buffer, which was caused by a skip (ultra small timing segment). So I was looking at wrong place for some time.

New version contains a fix for it. Please check and close the issue if it's solved.

Maik

**Comment by adrianbear** [comment]
Yeah, the windows build is taking a while

**Comment by MaikStohn** [comment]
Finally the build was getting through. v0.6.4 is ready now.

**Comment by adrianbear** [comment]
This appears to be resolved in version 0.6.4. Closing the issue :)
Adrian
