### ISSUE TITLE
Deceleration / Retraction issue (or user calibration required)

### ISSUE THREAD

**Issue by adrianbear** [MaikStohn/UP3D#29]
Hi @MaikStohn , @kscheff ,
I'm not sure if this is an issue or not. It is possible I just need to learn how to calibrate retraction settings for my printer.

But, with a standard preview from Simplify3d I can see a retraction point at this junction.
![image](https://cloud.githubusercontent.com/assets/6194143/15147129/2b85dc02-16fe-11e6-9e00-2178d09e24c5.png)
Of course, gcode does not show accelerations or decelerations, so I wont bother adding a screenshot with the retraction removed.
But after converting to up code and then back to gcode (and removing the retraction point) I can see the deceleration (and acceleration).
![image](https://cloud.githubusercontent.com/assets/6194143/15147184/724a713e-16fe-11e6-847f-7ae4bd1c3d3b.png)
In my real print, this is resulting in a disconnected tube (i.e. a C tube instead of an O tube).
![image](https://cloud.githubusercontent.com/assets/6194143/15147242/ccb27ed2-16fe-11e6-9e54-8218cb3d2f16.png)
The gap shown here is tough to get in a photo, but it runs the entire length of the print.

Is this an issue? Or is it just some retraction calibration settings I should amend?
If it's just retraction settings can you advise on a good technique to calibrate these?

Thanks
Adrian

**Comment by MaikStohn** [comment]
Hi, 

retraction is only used to prevent "stringing" thin plastic lines coming out of nozzle during travel moves.

So missing material can only be if a travel move ended at the start point and re-retraction was to fast and no pressure was in nozzle. From a previous file I remember that you had a very very high retraction speed. Usually I use 20mm/sec and 1mm distance. UP software uses 5mm distance and also a very slow speed.

Maik

**Comment by adrianbear** [comment]
I'm still not sure this is not an issue because the "gap" is not present if I print with version 0.3.0.
However I have found I can work around the problem by adding a retract distance of 2mm, an extra restart distance of 0.1mm and a retract speed of 1800mm/min. So I'm going to close the issue.
Thanks
Adrian

**Comment by MaikStohn** [comment]
Hi,

i made some test prints and also noticed a strange behavior.

I got a new idea and will rework the calculation.

Maik

**Comment by MaikStohn** [comment]
There was a bug causing this in v0.6.x

I reimplemented the complete calculation based on discussion with @adrian and @kscheff in other issue.

v0.7.0 is now very very precise and also don't have this retract bug.

Maik
