### ISSUE TITLE
UP3DTOOLS on mac

### ISSUE THREAD

**Issue by peters5555** [MaikStohn/UP3D#34]
Hi,
Not sure if it's just me but I get this error when trying to run the transcoder.

![screen shot 2016-06-15 at 9 26 20 am](https://cloud.githubusercontent.com/assets/19942633/16067012/be2b43bc-32fb-11e6-9702-b4bbd326431f.png)

**Comment by dfyx** [comment]
You have to run `./up3dtranscode` instead of just `up3dtranscode`. Otherwise OS X will look for the command in its standard paths instead of your local path. That's a general behavior of unix-like systems and has nothing to do with this project.

**Comment by peters5555** [comment]
Thanks for your help. As you can tell I’m not a programmer, but love using 3D printers. Please let me know if there is another area I should be in to get help or give feedback using UP3DTOOLS.

**Comment by dfyx** [comment]
You're welcome and I'm sorry if my comment sounded harsh (English is not my native language).

I just wanted to make it clear that this is not a problem with UP3DTOOLS.

**Comment by peters5555** [comment]
No worries:)
This e-mail and any attachments are intended for the addressee(s) only and may be confidential. Unauthorised use of this e-mail or its contents is strictly prohibited. If you are not the intended recipient please contact the sender as soon as possible by return e-mail and then please delete both messages. This notice should not be removed.
